title: <p align="center"> Anusha Chaudhuri </p>
logo: /assets/img/anusha-photo.jpg
description:
  <p align="center">
  <br>   
  Experienced software developer and data scientist, with expertise in Python, Data Science, Artificial Intelligence, Machine Learning, crafting high-impact, innovative solutions with cutting-edge technologies to drive business excellence
  <br>
  </p>
