title: <p align="center"> Anusha Chaudhuri </p>
logo: /assets/img/anusha-photo.jpg
description:
  <p align="center">
  <br>   
  Passionate AI/ML enthusiast and experienced Developer in the IT industry, crafting high-impact, innovative solutions with cutting-edge technologies to drive business excellence.
  <br>
  <br><br>
    Blogs
    <br>
    <a href="https://medium.com/@chaudhuri.anusha1/cosine-similarity-for-natural-language-processing-from-words-to-vectors-2b5a9ddfec69" target="_blank">Cosine Similarity For Natural Language Processing — From Words To Vectors</a><br>
    <a href="https://medium.com/@chaudhuri.anusha1/a-beginners-basic-guide-to-linear-regression-starting-from-the-straight-line-b73a2ea0128c" target="_blank">Linear Regression — Starting From The Straight Line</a><br>
    <a href="https://medium.com/@chaudhuri.anusha1/demystifying-machine-learning-evaluation-metrics-precision-recall-roc-and-more-e84d51b57766" target="_blank">Demystifying Machine Learning Evaluation Metrics — Precision, Recall, ROC And More</a>
  </p>
