title: <p align="center"> Anusha Chaudhuri </p>
logo: /assets/img/anusha-photo.jpg
description:
  <p align="center">
  <br>   
  Experienced Developer, AI Engineer, Data Scientist, with expertise in Python, Data Science, Artificial Intelligence, Machine Learning, Generative AI. Skilled in crafting high-impact solutions to drive business excellence.
  <br>
  </p>
